version: '3.6'

services:
  classroom-api:
    container_name: backend-container
    # image: node:8.11.1
    build: ./
      #context: ./backend
      #dockerfile: ./Dockerfile
    command: npm start
    working_dir: /app
    ports:
      - "3000:3000"
      
    